eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer‐ip‐address: true                    # 将自己的IP地址注册到服务中
    lease-renewal-interval-in-seconds: 10     # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）
server:
  port: 8005
spring:
  application:
    name: zipkin-server